### ISSUE TITLE
XCode build fails with "Path does not exist: www/"

### ISSUE THREAD

**Issue by drauschenbach** [jakecraige/ember-cli-cordova-example-app#2]
Using Ember-CLI 0.0.41, the XCode build Phase "Copy www directory" fails with this:

````
Path does not exist: www/
Command /bin/sh failed with exit code 1
````

**Comment by jakecraige** [comment]
I just pushed an update that upgrades this to the latest version of ember-cli. Can you give this a shot now?

**Comment by drauschenbach** [comment]
Just pulled the latest and gave it a try.

````
$ git pull
$ rm -rf node_modules bower_modules
$ npm install
$ bower install
$ ember build
version: 0.1.12
Building...
ember-cli-cordova: /Users/davidr/workspaces/ember-cli-cordova-example-app/cordova/platforms/ios/www/cordova.js did not exist. It is required for Device LiveReload to work.
````

**Comment by jakecraige** [comment]
Try running `ember cdv:build` first. I believe that will create the file for you

**Comment by jakecraige** [comment]
My bad, this is an open issue that hasn't been resolved. See https://github.com/poetic/ember-cli-cordova/issues/104 for how to fix this

**Comment by redolent** [comment]
To anyone else reading this with the same problem, `cordova build ios` resolved my problem. Sometimes `cordova build` doesn't do the trick.

**Comment by signalpoint** [comment]
Although I am not using ember, I still was running into the same error when trying to use cordova and xcode for iOS:

> Path does not exist: www

This is what worked for me:
```
# close xcode
cd my-app
cordova prepare ios
# open xcode
# run app
```

This is what **DID NOT** work for me:
```
# close xcode
cd my-app
cordova prepare ios
cordova clean
# open xcode
# run app
```

I kept thinking I needed the two cordova commands, but I think the `clean` is what was causing the problem, and only the `prepare` command is needed. I also hate to say it, but this *may* have contributed to the solution as well. These were run **before** the fix above:
```
# close xcode
cd my-app
cordova platform remove ios
cordova platform add ios
```

I also made sure that my app's project directory file system owner/group was properly set to my username/group.
